# Generated by Django 5.0.6 on 2024-05-12 04:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Polera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotografia', models.ImageField(upload_to='poleras/')),
                ('nombre', models.CharField(max_length=50)),
                ('talla', models.CharField(choices=[('XS', 'Extra Pequeña'), ('S', 'Pequeña'), ('M', 'Mediana'), ('L', 'Grande'), ('XL', 'Extra Grande')], max_length=2)),
                ('color', models.CharField(max_length=10)),
                ('precio', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('stock', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
            ],
        ),
    ]
