# Generated by Django 5.0.6 on 2024-05-12 07:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poleras', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polera',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='polera',
            name='talla',
        ),
        migrations.AddField(
            model_name='polera',
            name='stock_L',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AddField(
            model_name='polera',
            name='stock_M',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AddField(
            model_name='polera',
            name='stock_S',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AddField(
            model_name='polera',
            name='stock_XL',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999)]),
        ),
    ]
